FROM node:24-alpine

WORKDIR /app
COPY ./package.json .
RUN npm install
COPY . .
ARG PUBLIC_API_URL=http://localhost:3000/api/v1
ENV PUBLIC_API_URL=${PUBLIC_API_URL}

EXPOSE 3000
CMD ["npm", "run", "dev"]
