#cloud-config
package_update: true
package_upgrade: true

chpasswd:
  expire: false

packages:
  - qemu-guest-agent
  - zip
  - unzip
  - curl
  - wget
  - net-tools
  - openssh-server
  - ca-certificates
  - gnupg
  - git
  - lsb-release
  - software-properties-common
  - apt-transport-https

users:
  - name: lgtm
    ssh_authorized_keys:
      - "<SSH_KEY>"
    groups: users, sudo
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    lock_passwd: false
    passwd: "<PASSWD_HASH>"

runcmd:
  - systemctl enable --now qemu-guest-agent
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - . /etc/os-release && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - systemctl enable --now docker
  - usermod -aG docker lgtm
  - docker --version
  - docker compose version
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/$(dpkg --print-architecture)/kubectl"
  - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  - curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash
  - mount -t 9p -o trans=virtio,version=9p2000.L iot /mnt
