name: ft_lgtm

networks:
  ft_lgtm:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    networks:
      - ft_lgtm
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - OTEL_SERVICE_NAME=backend
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-lgtm:4317
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        mode: non-blocking

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        PUBLIC_API_URL: http://localhost:3000/api/v1
    container_name: frontend
    restart: unless-stopped
    networks:
      - ft_lgtm
    ports:
      - "5173:5173"
    environment:
      - PUBLIC_API_URL=http://localhost:3000/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules

  otel-lgtm:
    image: grafana/otel-lgtm:latest
    container_name: otel-lgtm
    restart: unless-stopped
    networks:
      - ft_lgtm
    ports:
      - "3001:3000"
      - "3100:3100"
      - "3200:3200"
      - "4040:4040"
      - "4317:4317"
      - "4318:4318"
      - "9090:9090"

  ipfs-service:
    image: ipfs/kubo:latest
    container_name: ipfs
    restart: unless-stopped
    networks:
      - ft_lgtm
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
