// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionStatus } from "./ExecutionStatus";

export type ExecuteResponse = { status: ExecutionStatus, stdout: string, stderr: string, compilation_log: string, execution_time_ms: bigint, ipfs_cid: string | null, };
