// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunResult = { stdout: string, stderr: string, error_message: string | null, execution_time_ms: bigint, fuel_consumed: bigint, };
